version: '3.7'
services:
  future_tech_dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: future_tech_dev
    env_file:
      - .env
    command: bash -c "npm run start:dev"
    tty: true
    ports:
      - "${PORT}:${PORT}"
    restart: always
#    volumes:
#      - .:/app
#      - /app/node_modules
    networks:
      - future-net

networks:
  future-net:
    external: true