version: '3.7'
services:
  future_cache:
    image: redis:6.2-alpine
    restart: always
    container_name: future_cache
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - future-net
  future_mongodb:
    image: mongo:latest
    container_name: future_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - future-net
networks:
  future-net:
    external: true